-- V6: веб-чат дашборда. История — на каждый клиентский ключ отдельным тредом
-- (title по умолчанию — первые символы первого сообщения).

CREATE TABLE IF NOT EXISTS chat_thread (
  client_key TEXT    PRIMARY KEY,
  title      TEXT    NOT NULL DEFAULT '',
  updated_at BIGINT  NOT NULL
);

CREATE TABLE IF NOT EXISTS chat_message (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_key TEXT    NOT NULL,
  role       TEXT    NOT NULL,             -- user | assistant
  content    TEXT    NOT NULL,
  created_at BIGINT  NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_chat_message_key ON chat_message(client_key, id);
