#!/bin/sh
# Local claudeproxy build: assemble a portable run folder - jar + config with server port 9090.
# The database path is relative to the launch directory: copy build/local outside
# the repository to keep the local proxy database out of the project.
set -e
cd "$(dirname "$0")/.."

if command -v npm >/dev/null 2>&1; then
    echo "[build-local] Building dashboard..."
    ./gradlew buildDashboard --console=plain
else
    echo "[build-local] npm not found - dashboard is not rebuilt (if web/dist exists, it will be served as is)."
fi

./gradlew bootJar --console=plain

RUN_DIR=build/local
mkdir -p "$RUN_DIR/config"
cp app/build/libs/claudeproxy-0.0.1-SNAPSHOT.jar "$RUN_DIR/claudeproxy.jar"

cat > "$RUN_DIR/config/application.yml" <<'EOF'
# Local claudeproxy configuration generated by scripts/build-local.
server:
  port: 9090
# The database path resolves against the launch directory.
# Copy this folder outside the repository to keep the DB out of the project.
spring:
  datasource:
    url: jdbc:sqlite:data/claudeproxy.db
EOF

echo ""
echo "[build-local] Done: build/local/claudeproxy.jar - server port 9090"
echo "[build-local] Run from the folder: java -jar claudeproxy.jar"
