@echo off
rem Local claudeproxy build: assemble a portable run folder - jar + config with server port 9090.
rem The database path is relative to the launch directory: copy build\local outside
rem the repository to keep the local proxy database out of the project.
setlocal
set "PROJECT_ROOT=%~dp0.."
cd /d "%PROJECT_ROOT%"

where npm >nul 2>nul
if %errorlevel%==0 (
    echo [build-local] Building dashboard...
    call "%PROJECT_ROOT%\gradlew.bat" buildDashboard --console=plain
    if errorlevel 1 goto :error
) else (
    echo [build-local] npm not found - dashboard is not rebuilt ^(if web/dist exists, it will be served as is^).
)

call "%PROJECT_ROOT%\gradlew.bat" bootJar --console=plain
if errorlevel 1 goto :error

set "RUN_DIR=%PROJECT_ROOT%\build\local"
if not exist "%RUN_DIR%\config" mkdir "%RUN_DIR%\config"
copy /y "%PROJECT_ROOT%\app\build\libs\claudeproxy-0.0.1-SNAPSHOT.jar" "%RUN_DIR%\claudeproxy.jar" >nul
if errorlevel 1 goto :error

> "%RUN_DIR%\config\application.yml" (
    echo # Local claudeproxy configuration generated by scripts/build-local.
    echo server:
    echo   port: 9090
    echo # The database path resolves against the launch directory.
    echo # Copy this folder outside the repository to keep the DB out of the project.
    echo spring:
    echo   datasource:
    echo     url: jdbc:sqlite:data/claudeproxy.db
)

echo.
echo [build-local] Done: build\local\claudeproxy.jar - server port 9090
echo [build-local] Run from the folder: java -jar claudeproxy.jar
exit /b 0

:error
echo [build-local] Build failed.
exit /b 1
